apiVersion: v1
kind: Service
metadata:
  name: java-docker-service
spec:
  selector:
    app: java-docker
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-docker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-docker
  template:
    metadata:
      labels:
        app: java-docker
    spec:
      containers:
      - name: java-docker
        image: spbravo/gitops:latest
        ports:
        - containerPort: 80
