apiVersion: apps/v1
kind: Service
metadata:
  name: java-docker-service
spec:
  type: NodePort
  selector:
    app: java-docker
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-docker-deployment
  labels:
    app: java-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-docker
  template:
    metadata:
      labels:
        app: java-docker
    spec:
      containers:
      - name: java-docker
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 8080
